title:               Seoyeon Lee
## Al-folio config
first_name: Seoyeon
last_name: Lee


enable_navbar_social: true
enable_darkmode: true
enable_progressbar: true
navbar_fixed: true

include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
# You may need to change the base URL depending on your deploy configuration.
baseurl:             '/garden'

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

max_width: 930px

sass:
  sass_dir: _sass
  style: compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

enable_navbar_social: false
enable_darkmode: true
enable_progressbar: true

navbar_fixed: true

search_enabled: false

# 메뉴 구성 예시
nav_pages:
  - title: "CV"
    url: "/cv/"
  - title: "Blog"
    url: "/blog/"
